### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by wangbq18** [hitvoice/RE2#1]
hello, I run the train.py. But  a mistake has occurred at map_, mrr = [float(s[-6:]) for s in stdout.strip().split('\n')].  ValueError:could not convert string to float.

**Comment by hitvoice** [comment]
Hi, could you please provide the configuration you use?  For WikiQA dataset, you should prepare the evaluation scripts as described in [this section](https://github.com/hitvoice/RE2#wikiqa)

**Comment by wangbq18** [comment]
> 
> 
> Hi, could you please provide the configuration you use? For WikiQA dataset, you should prepare the evaluation scripts as described in [this section](https://github.com/hitvoice/RE2#wikiqa)

I found the reason, Thanks!

**Comment by ellabee7** [comment]
@wangbq18 Hello, I just encountered the same issue, could you please share what was the problem in your case?

**Comment by ellabee7** [comment]
Found the solution. The problem is that the evaluation scripts already include compiled files, and running `make` will just say that everything is up-to-date, so it doesn't compile, and the already included `trec_eval` binary won't work. Had to force the make to rebuild with `make -B`.

**Comment by hitvoice** [comment]
It's correct. I've updated ReadMe to suggest the `make -B` command. Thanks!
