### ISSUE TITLE
sqrt在0处不可导，不用添加一个eps保持数值稳定吗？

### ISSUE THREAD

**Issue by alkaideemo** [hitvoice/RE2#2]
https://github.com/alibaba-edu/simple-effective-text-matching/blob/0a42712e4c46432dd4e836bedabbcf989ad30a8b/src/modules/__init__.py#L35
```python
w_norm = tf.sqrt(tf.maximum(tf.reduce_sum(tf.square(w), axis=list(range(len(shape) - 1)), keep_dims=True), eps)) 
```

**Comment by hitvoice** [comment]
注意看代码下一行：
```python
w = w / tf.maximum(w_norm, 1e-7) * g
```
如果w中真的出现一行全0的值，也会被1e-7这个常数取代，不会有导数传播，因此不会出现数值稳定性问题。

**Comment by alkaideemo** [comment]
感谢解答。
