### ISSUE TITLE
关于evaluate方式的问题

### ISSUE THREAD

**Issue by Berlin-98** [hitvoice/RE2#6]
您好，代码中使用的evaluate的方式我理解是通过加载回参数，重新实例化了一个model对象进行的。请问为什么不用restore或是读取meta保存的图结构的方式呢？

**Comment by hitvoice** [comment]
这里我理解的是保存阶段并没有保存计算图，只保存了参数值，所以需要先实例化一个对象把计算图构建出来。

**Comment by Berlin-98** [comment]
> 这里我理解的是保存阶段并没有保存计算图，只保存了参数值，所以需要先实例化一个对象把计算图构建出来。

在src/model.py中定义了self.saver = tf.train.Saver()，在save函数中调用该saver，saver保存了图结构，在训练完后models/quora/benchmark/中存储了checkpoint-xxxx.meta的文件，所以我觉得图结构应该是保存了的。我在浏览博客时看到通过从meta文件中进行恢复的做法比较常见，所以想知道以对象构造出图结构有别的优势吗？

**Comment by hitvoice** [comment]
除了方便在evaluate的过程中额外插入一些debug和可视化的节点以外，应该没有别的优势 :)

**Comment by Berlin-98** [comment]
> 除了方便在evaluate的过程中额外插入一些debug和可视化的节点以外，应该没有别的优势 :)

明白啦，谢谢！
